# Generated by Django 4.0.3 on 2022-04-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('details', models.TextField()),
                ('availabe', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100)),
            ],
        ),
    ]
